name: simone
channels:
  - pytorch
  - anaconda
  - nvidia
  - defaults
dependencies:
  - python>=3.9
  - pip>=21.1
  - ipython
  - pytorch
  # - cpuonly
  - torchvision
  - cudatoolkit>=11.1
  - cudnn>=8.2
  - cuda-nvcc
  - pip:
    - datasets
    - distrax
    - clu
    - einops
    - flax
    - treex
    - pytorch_lightning
    - positional-encodings
    - tap
    - ipdb
